# Generated by Django 3.0.3 on 2022-07-02 06:27

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end',
            field=models.DateTimeField(default=api.models.get_deadline),
        ),
        migrations.AddField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
